server:
  port: 8002
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml #mybatis配置文件所在路径
  type-aliases-package: com.mine.siis.entities #所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml  #mapper映射文件
spring:
  application:
    name: microservicecloud-dept #这个名字很重要
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver #mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb02 #数据库名称
    username: cloud
    password: cloud
    dbcp2:
      min-idle: 5 #数据库连接池的最小维持连接数
      initial-size: 5 #初始化连接数
      max-total: 5     #最大连接数
      max-wait-millis: 200
      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8002
    prefer-ip-address: true
    status-page-url-path: /info
info: 
  app.name: mine-microservicecloud
  company.name: www.mine.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  


